# Generated by Django 5.1.2 on 2025-01-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Reasonforappointment',
            field=models.TextField(max_length=100),
        ),
    ]
