# Generated by Django 5.1.2 on 2025-02-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_appointment_doctor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor_name',
            field=models.CharField(default='Dr. name', max_length=255),
        ),
    ]
